#!/bin/sh

# exec from container

if test -f ./goflow/conf/dev/docker.sh ; then
  . ./goflow/conf/dev/docker.sh
fi

printf "Installing the dev stack...\n\n"

dev_install_container_stack

printf "\n\nInstall finished!\n"